apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wsc3cfrbs-nodejs 
  janus-idp.io/tekton: wsc3cfrbs-nodejs
  backstage.io/kubernetes-id: wsc3cfrbs-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wsc3cfrbs-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  