apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wsc3cfrbs-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wsc3cfrbs-nodejs 
  name: wsc3cfrbs-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wsc3cfrbs-nodejs 
